name: Run Dagger Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dagger-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Set up Dagger
        uses: dagger/dagger-for-github@v7

      - name: Run Dagger Pipeline
        run: |
          cd dagger
          go mod download
          dagger run go run pipeline.go

      - name: Run Model Inference Test Action
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
